### ISSUE TITLE
Microsoft Secure Boot support

### ISSUE THREAD

**Issue by daniel-dressler** [etherealvisage/kbase#1]
Hey I am trying to run this on my iPhone. It said something about the TPM. How do I run this through Intel Trusted Computing?

Code please.

**Comment by etherealvisage** [comment]
Thanks for your interest! I should note that this repository is intended to be part of an upcoming online course I'm planning on teaching on OpenLearning, and I wasn't expecting to get any questions or feedback for a little while to come.

I'm slightly confused by the "iPhone" part of your question — insofar as I'm aware, Apple's mobile product line only uses ARM-based processors, and this repository is for Intel/AMD x86_64 processors?

I'm not certain what you mean by TPM here. The TPM is a general co-processor used on many modern systems (typically a very low-power ARM core on the motherboard) to provide a trusted root that can be used to check firmware and operating system signatures. I suspect the problem you're running into is with UEFI's Secure Boot, which uses the TPM?

If you're looking to support UEFI Secure Boot, well . . . your best bet is probably to go the route of using [Canonical's GRUB secure boot shim](https://wiki.ubuntu.com/SecurityTeam/SecureBoot) or similar. If you're interested, I can write up something on the topic.

**Comment by daniel-dressler** [comment]
Sorry Ethereal I just meant this to tease you. Eric mentioned your Kernel from scratch efforts ages ago and I thought your account was Eric's when this appeared in my notification timeline.
